### ISSUE TITLE
NgramModel???

### ISSUE THREAD

**Issue by imajeed** [rossgoodwin/poetizer#1]
Hi, I'm trying to use Poetizer to generate poetry out of a corpus I've been preparing.

I'm running Python 2.7 with nltk installed on a Macbook Air.

Here's what happens:

Imaads-MacBook-Air:poetizer-master imaadmajeed$ python poetizer.py languagebill.txt ABABCD
importing source text...
reading source text...
tokenizing words...
making word list...
extracting words from word list...
compiling rhymes...
building content model...
Traceback (most recent call last):
  File "poetizer.py", line 432, in <module>
    content_model = nltk.NgramModel(3, vw, estimator=estimator)
AttributeError: 'module' object has no attribute 'NgramModel'
Imaads-MacBook-Air:poetizer-master imaadmajeed$ 

How should I approach this? Please let me know.

**Comment by rossgoodwin** [comment]
Unfortunately, NLTK has discontinued the NgramModel module since I wrote that code. (If I were going to rewrite this code now, I would've just implemented the NgramModel from scratch, since it's not all that complicated.) But if you want to run the code as-is, this branch of NLTK includes the missing module and should do the trick: https://github.com/nltk/nltk/tree/model

**Comment by imajeed** [comment]
Okay, now this is what turns up:

Imaads-MacBook-Air:poetizer-master imaadmajeed$ python poetizer.py corpus.txt 80
importing source text...
reading source text...
tokenizing words...
making word list...
extracting words from word list...
building content model...
Traceback (most recent call last):
  File "poetizer.py", line 432, in <module>
    content_model = nltk.NgramModel(3, vw, estimator=estimator)
AttributeError: 'module' object has no attribute 'NgramModel'

**Comment by sarah-as-share** [comment]
NgramModel is deprecated in nltk.

I have a (currently) running version of the poetizer: https://github.com/sarah-as-share/poetizer/
